extends: ./tspconfig.yaml
options:
  '@typespec/json-schema':
    emitter-output-dir: '{project-root}/../../schema/next'
    file-type: 'json'
  '@linzjs/typespec-emitter':
    typescript-output-file: '{project-root}/src/types/next.ts'
    parquet-output-dir: '{project-root}/src/types/next/parquet/'
