name: 'Python CI'
description: 'Lint, test and type check Python code'

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      run: uv sync --all-extras --dev

    - name: Lint
      shell: bash
      run: uv run ruff check

    - name: Format
      shell: bash
      run: uv run ruff format --check

    - name: Type check
      shell: bash
      run: uv run mypy .

    - name: Test
      shell: bash
      run: uv run pytest || [ $? -eq 5 ]
