/**
 * This file was automatically generated by the TypeSpec TypeScript emitter.
 * Do not edit this file manually.
 *
 * Points to the latest schema version (v0.4).
 */

export * from './v0.4/index.ts';

export * as v0_3 from './v0.3/index.ts';
export * as v0_4 from './v0.4/index.ts';
