/**
 * This file was automatically generated by the TypeSpec TypeScript emitter.
 * Do not edit this file manually.
 */

export type BridgeSubtype = 'foot_traffic' | 'train';

export type BridgeType = 'cablecar' | 'farm' | 'foot_traffic' | 'train' | 'vehicle';

export type BuildingStatus = 'derelict' | 'historic' | 'private';

export type BuildingSubtype =
  | 'abattoir'
  | 'camp'
  | 'cement_works'
  | 'church'
  | 'energy_facility'
  | 'factory'
  | 'fertiliser_works'
  | 'fire_lookout'
  | 'forest_headquarters'
  | 'gas_compound'
  | 'greenhouse'
  | 'gun_club'
  | 'gun_emplacement'
  | 'hall'
  | 'homestead'
  | 'hospital'
  | 'hut'
  | 'lodge'
  | 'marae'
  | 'mill'
  | 'museum'
  | 'observatory'
  | 'polytechnic'
  | 'power_generation'
  | 'prison'
  | 'private_hut'
  | 'salt_works'
  | 'school'
  | 'shingle_works'
  | 'silo'
  | 'stamping_battery'
  | 'substation'
  | 'surf_club'
  | 'university'
  | 'visitor_centre'
  | 'water_treatment_plant';

export type CartoCharplace = '' | 'CharactersAtVertices' | 'StretchCharacterSpacingToFit' | 'StretchWordSpacingToFit';

export type CartoColour = '' | 'black' | 'process_blue' | 'red';

export type CartoFont = '' | 'Nimbus Sans LINZ';

export type CartoPlacement = '' | 'AL' | 'BL' | 'OL';

export type CartoStyle = '' | 'Italic' | 'Narrow' | 'Narrow Bold' | 'Narrow Italic' | 'Regular';

export type CartoTextanchor = '' | 'centre' | 'left' | 'left ' | 'left 0.62' | 'right';

export type CartoTextfont =
  | 'ATTrium-Italic'
  | 'ATTriumMou-Cond'
  | 'ATTriumMou-CondBold'
  | 'ATTriumMou-CondItalic'
  | 'ATTriumMou-Italic'
  | 'ATTriumMou-Regular'
  | 'Courier Bold Oblique';

export type ConstructionType = 'suspension' | 'swing' | 'trestle';

/**
 * This enum will be redone in another work item - keeping as is for now
 */
export type DisplayEnum = '0' | '1' | '2' | '3';

export type GridDirection = 'x' | 'y';

export type LandcoverPointCoreType = 'cemetery' | 'fumarole' | 'swamp';

export type LandcoverType = 'ice' | 'moraine' | 'moraine_wall' | 'mud' | 'sand' | 'scree' | 'shingle' | 'swamp';

export type LanduseStatus = 'dangerous' | 'disused' | 'old';

export type LanduseSubtype = 'training' | 'opencast' | 'underground';

export type LanduseType =
  | 'cemetery'
  | 'cycle_track'
  | 'dog_track'
  | 'golf_course'
  | 'gravel_pit'
  | 'horse_track'
  | 'landfill'
  | 'mine'
  | 'orchard'
  | 'pumice_pit'
  | 'quarry'
  | 'racetrack'
  | 'rifle_range'
  | 'showground'
  | 'sportsfield'
  | 'vineyard'
  | 'vehicle_track';

export type MetadataSource = 'nzgb_gazetteer' | 'linz_aims';

export type PlaceComposition = 'limestone' | 'pumice' | 'coral';

export type PlaceSubtype = 'opencast' | 'underground';

export type PlaceType = 'cave' | 'cemetery' | 'grave' | 'historic_site' | 'mine' | 'monument' | 'pa';

export type RailwayStatus = 'disused';

export type RailwaySubtype = 'siding';

export type RailwayTrackType = 'single' | 'multiple';

export type RailwayVehicleType = 'train' | 'tram' | 'rail_cart' | 'cablecar';

export type ReliefLineSubtype = 'causeway' | 'stopbank';

export type ReliefLineType =
  | 'cliff_edge'
  | 'cutting_edge'
  | 'embankment'
  | 'rapid'
  | 'slip_edge'
  | 'waterfall'
  | 'waterfall_edge'
  | 'seawall';

export type ReliefPointType = 'height' | 'saddle' | 'sinkhole' | 'waterfall';

export type RoadStatus = 'under_construction' | 'closed';

export type RoadSurface = 'metalled' | 'unmetalled' | 'sealed';

export type RockOutcropSubtype = 'small_rock_outcrop' | 'large_rock_outcrop' | 'large_boulder';

export type RunwayStatus = 'disused';

export type RunwaySubtype = 'aerodrome' | 'airport' | 'airstrip';

export type RunwaySurface = 'grass' | 'sealed';

export type Status =
  | 'closed'
  | 'dangerous'
  | 'derelict'
  | 'disused'
  | 'historic'
  | 'locked'
  | 'old'
  | 'private'
  | 'remains'
  | 'ruins'
  | 'under_construction';

export type StructureLineType =
  | 'boatramp'
  | 'boom'
  | 'breakwater'
  | 'cableway_industrial'
  | 'cableway_people'
  | 'dam'
  | 'flume'
  | 'ladder'
  | 'marine_farm'
  | 'ski_lift'
  | 'ski_tow'
  | 'slipway'
  | 'spillway_edge'
  | 'walkwire'
  | 'water_race'
  | 'weir'
  | 'wharf'
  | 'wharf_edge';

export type StructurePointType =
  | 'beacon'
  | 'bivouac'
  | 'buoy'
  | 'chimney'
  | 'dredge'
  | 'flare'
  | 'floodgate'
  | 'gate'
  | 'ladder'
  | 'mast'
  | 'radar_dome'
  | 'redoubt'
  | 'satellite_station'
  | 'shaft'
  | 'siphon'
  | 'stockyard'
  | 'tank'
  | 'tower'
  | 'well'
  | 'windmill'
  | 'wreck';

export type StructureSpecies = 'mussels' | 'salmon';

export type StructureStatus =
  | 'closed'
  | 'dangerous'
  | 'derelict'
  | 'disused'
  | 'historic'
  | 'locked'
  | 'old'
  | 'private'
  | 'remains'
  | 'ruins'
  | 'under_construction';

export type StructureSubtype =
  | 'building'
  | 'coal'
  | 'concrete'
  | 'disused'
  | 'fuel'
  | 'historic'
  | 'jetty'
  | 'lake'
  | 'land'
  | 'lighthouse'
  | 'lime'
  | 'locked'
  | 'plane'
  | 'power_generation'
  | 'rock'
  | 'sea'
  | 'ship'
  | 'surge_chamber'
  | 'tunnel_ventilation'
  | 'uncovered'
  | 'water';

export type StructureTankType = 'uncovered' | 'water' | 'surge_chamber';

export type StructureType = 'dry_dock' | 'fish_farm' | 'marine_farm' | 'reservoir' | 'siphon' | 'tank';

export type SubstanceExtracted =
  | 'bentonite'
  | 'clay'
  | 'coal'
  | 'gold'
  | 'gravel'
  | 'ironsand'
  | 'lime'
  | 'limestone'
  | 'metal'
  | 'quartz'
  | 'scheelite'
  | 'shingle'
  | 'silica_sand'
  | 'silver'
  | 'stone'
  | 'zeolite';

export type TrackStatus = 'closed';

export type TrackSubtype = 'cycle_only' | 'foot' | 'vehicle';

export type TrackType = 'connector' | 'multiple' | 'route' | 'single';

export type TunnelStatus = 'closed' | 'under_construction';

export type TunnelSubtype = 'natural';

export type TunnelUse = 'cablecar' | 'foot_traffic' | 'livestock' | 'river' | 'train' | 'tram' | 'vehicle';

export type UtilityPointType = 'dry_dock' | 'fish_farm' | 'marine_farm' | 'reservoir' | 'siphon' | 'tank';

export type UtilitySubtype = 'ironsand' | 'sewage' | 'steam' | 'water';

export type UtilitySupporttype = 'pole' | 'pylon';

export type UtilityVisibility = 'underground';

export type VegetationSubtype = 'coniferous' | 'non-coniferous';

export type WaterPerennial = 'dry' | 'seasonal';

export type WaterSubtype =
  | 'evaporation'
  | 'hydro_electric'
  | 'ice_skating'
  | 'oil'
  | 'oxidation'
  | 'reservoir'
  | 'settling'
  | 'sewage'
  | 'sewage_treatment'
  | 'sludge';

export type WaterTemperatureIndicator = 'cold' | 'hot';

export type WaterType = 'canal' | 'drain' | 'lagoon' | 'lake' | 'pond' | 'river' | 'soakhole' | 'spring' | 'waterfall';

export type LandcoverPoint = RockOutcrop | LandcoverPointCoreTypes;

export interface Airport {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'airport';
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

/**
 * GeoParquet 1.1 covering bbox struct.
 */
export interface BBox {
  xmin: number;
  ymin: number;
  xmax: number;
  ymax: number;
}

export interface BridgeLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: BridgeType | null;
  subtype: BridgeSubtype | null;
  construction_type: ConstructionType | null;
  status: Status | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Building {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'building';
  subtype: BuildingSubtype | null;
  status: BuildingStatus | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface BuildingPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'building';
  subtype: BuildingSubtype | null;
  status: BuildingStatus | null;
  name: string | null;
  orientation: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Coastline {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'coastline' | 'water_confluence' | 'wharf';
  elevation: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Contour {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'contour';
  elevation: number | null;
  definition: string | null;
  designation: 'supplementary' | null;
  formation: 'depression' | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface DataSource {
  /** Name of the column in this table where the linked data gets copied to */
  table_column: string;
  /** Registered source for linked data */
  source: MetadataSource;
  /** Name of the key column in source to use for linking */
  source_key_name: string;
  /** Value of the key column in source to use for linking. */
  source_key_value: number | string;
  /** Name of the table in source that contains the linked data */
  source_table: string;
  /** Name of the column in the source where the linked data gets copied from */
  source_column: string;
  /** Timestamp when the source was last updated */
  source_updated_at: string;
  /** Timestamp when this linked data was last imported */
  imported_at: string;
}

export interface DescriptiveText {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'descriptive_text';
  info_display: string | null;
  size: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface FenceLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'fence';
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface FerryLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'ferry_crossing';
  subtype: 'vehicle' | 'passenger' | 'freight' | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface GeographicName {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'geographic_name';
  name: string | null;
  desc_code: string | null;
  size: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface GeoParquet {
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Island {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'island';
  name: string | null;
  group_name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Landcover {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: LandcoverType;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface LandcoverLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'dredge_tailing';
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface LandcoverPointCoreTypes {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: LandcoverPointCoreType;
  subtype: null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Landuse {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: LanduseType;
  subtype: LanduseSubtype | null;
  status: LanduseStatus | null;
  name: string | null;
  substance_extracted: SubstanceExtracted | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface LanduseLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: LanduseType;
  subtype: LanduseSubtype | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface LandusePoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: LanduseType;
  subtype: LanduseSubtype | null;
  status: LanduseStatus | null;
  name: string | null;
  substance_extracted: SubstanceExtracted | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Marine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'mangrove' | 'reef' | 'rock' | 'shoal';
  name: string | null;
  composition: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface MarinePoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'rock';
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Nztopo50CartoText {
  /** UUIDv7 of the feature */
  id: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  /** id (UUID) of the example feature. */
  example_point_id: string | null;
  full_text: string | null;
  text_bend: number | null;
  text_char_spacing_distance: number | null;
  text_colour: number | null;
  text_font: CartoTextfont | null;
  text_height: number | null;
  text_orientation: number | null;
  text_placement: number | null;
  text_size_type: number | null;
  text_stretch_length: number | null;
  text_string: string | null;
  text_word_spacing_distance: number | null;
  font: CartoFont | null;
  style: CartoStyle | null;
  colour: CartoColour | null;
  size: number | null;
  placement: CartoPlacement | null;
  offset: number | null;
  textanchor: CartoTextanchor | null;
  labelanchor: number | null;
  charplace: CartoCharplace | null;
  chardistance: number | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Nztopo50DmsGrid {
  /** UUIDv7 of the feature */
  id: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  direction: GridDirection;
  value: number;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Nztopo50Grid {
  /** UUIDv7 of the feature */
  id: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  direction: GridDirection;
  value: number;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Nztopo50MapSheet {
  /** UUIDv7 of the feature */
  id: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'nztopo50_map_sheet';
  sheet_code: string;
  sheet_name: string;
  origin_x: number;
  origin_y: number;
  /** id (UUID) of the example feature. */
  example_point_id: string;
  published_version: string;
  published_at: string;
  updated_at: string;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface PlacePoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: PlaceType;
  subtype: PlaceSubtype | null;
  name: string | null;
  elevation: number | null;
  composition: PlaceComposition | null;
  description: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface ProductFeature {
  /** UUIDv7 of the feature */
  id: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
}

/**
 * All mainline railway lines are held in the Topo50 data and shown on the Topo50 printed maps.
 * Where a railway line is located close to a road, the line held in the data and shown on the printed map
 * may be offset from the road sufficient that the two symbols are recognisable at 1:50,000.
 *
 * Multiple sidings may be held in the data and shown on the printed maps as a single feature
 */
export interface RailwayLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'railway';
  subtype: RailwaySubtype | null;
  track_type: RailwayTrackType | null;
  vehicle_type: RailwayVehicleType | null;
  status: RailwayStatus | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface RailwayPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'station';
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Relief {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'waterfall' | 'rapid';
  name: string | null;
  height: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface ReliefLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: ReliefLineType;
  subtype: ReliefLineSubtype | null;
  name: string | null;
  height: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface ReliefPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: ReliefPointType;
  name: string | null;
  display: DisplayEnum | null;
  elevation: number | null;
  height: number | null;
  orientation: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface ResidentialArea {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'residential_area';
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface RoadLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'road';
  hierarchy: string | null;
  status: RoadStatus | null;
  name: string | null;
  highway_number: string | null;
  lane_count: number | null;
  surface: RoadSurface | null;
  way_count: 'one_way' | null;
  width_indicator: 'w' | null;
  road_access: 'mp' | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface RockOutcrop {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'rock_outcrop';
  subtype: RockOutcropSubtype;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Runway {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'runway';
  subtype: RunwaySubtype | null;
  status: RunwayStatus | null;
  surface: RunwaySurface | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Structure {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: StructureType;
  subtype: StructureSubtype | null;
  lid_type: 'covered' | null;
  tank_type: StructureTankType | null;
  species: StructureSpecies | null;
  status: StructureStatus | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface StructureLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: StructureLineType;
  subtype: StructureSubtype | null;
  species: StructureSpecies | null;
  status: StructureStatus | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface StructurePoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: StructurePointType;
  subtype: StructureSubtype | null;
  tank_type: StructureTankType | null;
  status: StructureStatus | null;
  name: string | null;
  height: number | null;
  orientation: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface TopographicFeature {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
}

export interface TopographicMetadata {
  metadata: DataSource[] | null;
}

export interface TrackLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'track';
  subtype: TrackSubtype | null;
  track_type: TrackType | null;
  status: TrackStatus | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface TransportPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'ford' | 'helipad';
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface TrigPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'trig';
  trig_type: 'beaconed' | null;
  name: string | null;
  code: string | null;
  elevation: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface TunnelLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'tunnel';
  tunnel_use: TunnelUse | null;
  tunnel_use2: TunnelUse | null;
  subtype: TunnelSubtype | null;
  status: TunnelStatus | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface UtilityLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'pipeline' | 'powerline' | 'telephone';
  subtype: UtilitySubtype | null;
  support_type: UtilitySupporttype | null;
  status: string | null;
  name: string | null;
  visibility: UtilityVisibility | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface UtilityPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: UtilityPointType;
  name: string | null;
  orientation: number | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Vegetation {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'exotic' | 'native' | 'scattered_scrub' | 'scrub';
  subtype: VegetationSubtype | null;
  species: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface VegetationLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'shelter_belt';
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface VegetationPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: 'tree' | 'scattered_scrub';
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface Water {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: WaterType;
  subtype: WaterSubtype | null;
  hierarchy: string | null;
  name: string | null;
  group_name: string | null;
  height: number | null;
  elevation: number | null;
  perennial: WaterPerennial | null;
  temperature_indicator: WaterTemperatureIndicator | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface WaterLine {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: WaterType;
  hierarchy: string | null;
  name: string | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}

export interface WaterPoint {
  /** UUIDv7 of the feature */
  id: string;
  created_at: string;
  updated_at: string;
  /**
   * Reference topo50 feature ID.
   *
   * Will be null if the feature is new and has not been published in a Topo50 edition.
   */
  t50_fid: number | null;
  type: WaterType;
  name: string | null;
  orientation: number | null;
  temperature_indicator: WaterTemperatureIndicator | null;
  metadata: DataSource[] | null;
  /** GeoParquet 1.1 covering geometry struct. */
  geometry: unknown;
  /** GeoParquet 1.1 covering bbox struct. */
  bbox?: BBox;
}
