/**
 * This file was automatically generated by the TypeSpec TypeScript emitter.
 * Do not edit this file manually.
 */

/**
 * Auto-derived from observed values of `bridge_use2`.
 */
export type BridgeUse2Enum = 'train';

/**
 * Auto-derived from observed values of `bridge_use`.
 */
export type BridgeUseEnum = 'cablecar' | 'farm' | 'foot traffic' | 'train' | 'vehicle';

/**
 * Auto-derived from observed values of `charplace`.
 */
export type CharplaceEnum = '' | 'CharactersAtVertices' | 'StretchCharacterSpacingToFit' | 'StretchWordSpacingToFit';

/**
 * Auto-derived from observed values of `colour`.
 */
export type ColourEnum = '' | 'black' | 'process_blue' | 'red';

/**
 * Auto-derived from observed values of `composition`.
 */
export type CompositionEnum = 'limestone' | 'pumice';

/**
 * Auto-derived from observed values of `construction_type`.
 */
export type ConstructionTypeEnum = 'suspension' | 'swing' | 'trestle';

/**
 * Auto-derived from observed values of `designation`.
 */
export type DesignationEnum = 'supplementary';

/**
 * Auto-derived from observed values of `direction`.
 */
export type DirectionEnum = 'x' | 'y';

/**
 * Auto-derived from observed values of `display`.
 */
export type DisplayEnum = '0' | '1' | '2' | '3';

/**
 * Auto-derived from observed values of `example_class`.
 */
export type ExampleClassEnum = 'geographic_name' | 'trig_pnt';

/**
 * Auto-derived from observed values of `font`.
 */
export type FontEnum = '' | 'Nimbus Sans LINZ';

/**
 * Auto-derived from observed values of `formation`.
 */
export type FormationEnum = 'depression';

/**
 * Auto-derived from observed values of `subtype`.
 */
export type LanduseSubTypeEnum = 'opencast' | 'training';

/**
 * Auto-derived from observed values of `landuse_use`.
 */
export type LanduseUseEnum = 'cycle' | 'dog' | 'horse' | 'vehicle';

/**
 * Auto-derived from observed values of `lid_type`.
 */
export type LidTypeEnum = 'covered';

/**
 * Auto-derived from observed values of `location`.
 */
export type LocationEnum = 'lake' | 'land' | 'sea';

/**
 * Auto-derived from observed values of `material_conveyed`.
 */
export type MaterialConveyedEnum = 'coal' | 'lime';

/**
 * Auto-derived from observed values of `material`.
 */
export type MaterialEnum = 'concrete' | 'rock';

/**
 * Auto-derived from observed values of `perennial`.
 */
export type PerennialEnum = 'dry' | 'seasonal';

/**
 * Auto-derived from observed values of `placement`.
 */
export type PlacementEnum = '' | 'AL' | 'BL' | 'OL';

/**
 * Auto-derived from observed values of `place_type`.
 */
export type PlaceTypeEnum = 'opencast' | 'underground';

/**
 * Auto-derived from observed values of `railway_use`.
 */
export type RailwayUseEnum = 'siding';

/**
 * Auto-derived from observed values of `relief_use`.
 */
export type ReliefUseEnum = 'causeway' | 'stopbank';

/**
 * Auto-derived from observed values of `restrictions`.
 */
export type RestrictionsEnum = 'locked';

/**
 * Auto-derived from observed values of `road_access`.
 */
export type RoadAccessEnum = 'mp';

/**
 * Auto-derived from observed values of `runway_use`.
 */
export type RunwayUseEnum = 'aerodrome' | 'airport' | 'airstrip';

/**
 * Auto-derived from observed values of `species`.
 */
export type SpeciesEnum = 'mussels' | 'salmon';

/**
 * Auto-derived from observed values of `status`.
 */
export type StatusEnum =
  | 'closed'
  | 'dangerous'
  | 'derelict'
  | 'disused'
  | 'historic'
  | 'locked'
  | 'old'
  | 'private'
  | 'remains'
  | 'ruins'
  | 'under construction';

/**
 * Auto-derived from observed values of `stored_item`.
 */
export type StoredItemEnum = 'fuel' | 'water';

/**
 * Auto-derived from observed values of `subtype`.
 */
export type StructureSubTypeEnum = 'lighthouse' | 'surge chamber' | 'uncovered' | 'water';

/**
 * Auto-derived from observed values of `structure_use`.
 */
export type StructureUseEnum = 'disused' | 'historic' | 'jetty' | 'power generation' | 'tunnel ventilation';

/**
 * Auto-derived from observed values of `style`.
 */
export type StyleEnum = '' | 'Italic' | 'Narrow' | 'Narrow Bold' | 'Narrow Italic' | 'Regular';

/**
 * Auto-derived from observed values of `substance`.
 */
export type SubstanceEnum =
  | 'bentonite'
  | 'clay'
  | 'coal'
  | 'gold'
  | 'gravel'
  | 'ironsand'
  | 'lime'
  | 'limestone'
  | 'metal'
  | 'quartz'
  | 'scheelite'
  | 'shingle'
  | 'silica sand'
  | 'silver'
  | 'stone'
  | 'zeolite';

/**
 * Auto-derived from observed values of `subtype`.
 */
export type SubTypeEnum = 'coniferous' | 'non-coniferous';

/**
 * Auto-derived from observed values of `support_type`.
 */
export type SupportTypeEnum = 'pole' | 'pylon';

/**
 * Auto-derived from observed values of `surface`.
 */
export type SurfaceEnum = 'grass' | 'metalled' | 'sealed' | 'unmetalled';

/**
 * Auto-derived from observed values of `temperature`.
 */
export type TemperatureEnum = 'hot';

/**
 * Auto-derived from observed values of `temperature_indicator`.
 */
export type TemperatureIndicatorEnum = 'cold' | 'hot';

/**
 * Auto-derived from observed values of `textanchor`.
 */
export type TextanchorEnum = '' | 'centre' | 'left' | 'left ' | 'left 0.62' | 'right';

/**
 * Auto-derived from observed values of `text_font`.
 */
export type TextFontEnum =
  | 'ATTrium-Italic'
  | 'ATTriumMou-Cond'
  | 'ATTriumMou-CondBold'
  | 'ATTriumMou-CondItalic'
  | 'ATTriumMou-Italic'
  | 'ATTriumMou-Regular'
  | 'Courier Bold Oblique';

/**
 * Auto-derived from observed values of `track_type`.
 */
export type TrackTypeEnum = 'connector' | 'multiple' | 'route' | 'single';

/**
 * Auto-derived from observed values of `track_use`.
 */
export type TrackUseEnum = 'cycle only' | 'foot' | 'vehicle';

/**
 * Auto-derived from observed values of `trig_type`.
 */
export type TrigTypeEnum = 'beaconed';

/**
 * Auto-derived from observed values of `subtype`.
 */
export type TunnelSubTypeEnum = 'natural';

/**
 * Auto-derived from observed values of `tunnel_use2`.
 */
export type TunnelUse2Enum = 'livestock';

/**
 * Auto-derived from observed values of `tunnel_use`.
 */
export type TunnelUseEnum = 'cablecar' | 'foot traffic' | 'livestock' | 'river' | 'train' | 'tram' | 'vehicle';

/**
 * Auto-derived from observed values of `infrastructure_use`.
 */
export type UtilityUseEnum = 'ironsand' | 'sewage' | 'steam' | 'water';

/**
 * Auto-derived from observed values of `vehicle_type`.
 */
export type VehicleTypeEnum = 'cablecar' | 'rail cart' | 'train' | 'tram';

/**
 * Auto-derived from observed values of `visibility`.
 */
export type VisibilityEnum = 'underground';

/**
 * Auto-derived from observed values of `water_use`.
 */
export type WaterUseEnum =
  | 'evaporation'
  | 'hydro-electric'
  | 'ice skating'
  | 'oil'
  | 'oxidation'
  | 'reservoir'
  | 'settling'
  | 'sewage'
  | 'sewage treatment'
  | 'sludge';

/**
 * Auto-derived from observed values of `way_count`.
 */
export type WayCountEnum = 'one way';

/**
 * Auto-derived from observed values of `wreck_of`.
 */
export type WreckOfEnum = 'plane' | 'ship';

export interface Airport {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'airport';
  name: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox: BBox;
}

/**
 * Capture / change-tracking columns shared by most features.
 */
export interface AuditFields {
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
}

/**
 * GeoParquet 1.1 covering bbox struct.
 */
export interface BBox {
  xmin: number;
  ymin: number;
  xmax: number;
  ymax: number;
}

export interface BridgeLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'bridge';
  bridge_use?: BridgeUseEnum | null;
  bridge_use2?: BridgeUse2Enum | null;
  construction_type?: ConstructionTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Building {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'building';
  building_use?: string | null;
  status?: StatusEnum | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface BuildingPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'building';
  building_use?: string | null;
  status?: StatusEnum | null;
  name?: string | null;
  orientation?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Coastline {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'coastline';
  coastline_type?: string | null;
  elevation?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

/**
 * Derived polygon Union of coastline and island
 */
export interface CoastlinePolygon {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'coastline' | 'island';
  coastline_type?: string | null;
  elevation?: number | null;
  name?: string | null;
  group_name?: string | null;
  /** WKB polygon geometry in NZGD2000 (EPSG:4167). */
  geometry: unknown;
}

export interface Contour {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: number | null;
  type: 'contour';
  elevation?: number | null;
  definition?: string | null;
  designation?: DesignationEnum | null;
  formation?: FormationEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface DescriptiveText {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'descriptive_text';
  nzgb_id?: unknown;
  info_display?: string | null;
  size?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface FenceLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'fence';
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface FerryCrossing {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'ferry_crossing';
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface GeographicName {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'geographic_name';
  name?: string | null;
  desc_code?: string | null;
  size?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Island {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'island';
  name?: string | null;
  group_name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Landcover {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'ice' | 'moraine' | 'moraine_wall' | 'mud' | 'rapid' | 'sand' | 'scree' | 'shingle' | 'swamp';
  subtype?: SubTypeEnum | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface LandcoverLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'dredge_tailing';
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface LandcoverPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'fumarole' | 'rock_outcrop' | 'swamp';
  name?: string | null;
  elevation?: number | null;
  display?: DisplayEnum | null;
  orientation?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Landuse {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type:
    | 'cemetery'
    | 'golf_course'
    | 'gravel_pit'
    | 'landfill'
    | 'mine'
    | 'orchard'
    | 'pumice_pit'
    | 'quarry'
    | 'racetrack'
    | 'rifle_range'
    | 'showground'
    | 'sportsfield'
    | 'vineyard';
  landuse_use?: LanduseUseEnum | null;
  subtype?: LanduseSubTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  substance_extracted?: SubstanceEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface LanduseLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'racetrack';
  landuse_use?: LanduseUseEnum | null;
  subtype?: LanduseSubTypeEnum | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Marine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'mangrove' | 'reef' | 'rock' | 'shoal';
  name?: string | null;
  composition?: CompositionEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Nztopo50CartoText {
  /** UUID for the feature. */
  id: string;
  /** id (UUID) of the example feature. */
  example_point_id?: string | null;
  full_text?: string | null;
  text_bend?: number | null;
  text_char_spacing_distance?: number | null;
  text_colour?: number | null;
  text_font?: TextFontEnum | null;
  text_height?: number | null;
  text_orientation?: number | null;
  text_placement?: number | null;
  text_size_type?: number | null;
  text_stretch_length?: number | null;
  text_string?: string | null;
  text_word_spacing_distance?: number | null;
  font?: FontEnum | null;
  style?: StyleEnum | null;
  colour?: ColourEnum | null;
  size?: number | null;
  placement?: PlacementEnum | null;
  offset?: number | null;
  textanchor?: TextanchorEnum | null;
  labelanchor?: number | null;
  charplace?: CharplaceEnum | null;
  chardistance?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Nztopo50DmsGrid {
  /** UUID for the feature. */
  id: string;
  direction?: DirectionEnum | null;
  value?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Nztopo50Grid {
  /** UUID for the feature. */
  id: string;
  direction?: DirectionEnum | null;
  value?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Nztopo50MapSheet {
  /** UUID for the feature. */
  id: string;
  t50_fid?: unknown;
  type: 'nztopo50_map_sheet';
  sheet_code: string;
  sheet_name: string;
  x_origin: number;
  y_origin: number;
  /** topo_id (UUID) of the example feature. */
  example_point_id: string;
  published_version: string;
  published_at: Record<string, unknown>;
  updated_at: Record<string, unknown>;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface PlacePoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type:
    | 'cave'
    | 'cemetery'
    | 'grave'
    | 'historic_site'
    | 'mine'
    | 'monument'
    | 'pa'
    | 'radar_dome'
    | 'saddle'
    | 'satellite_station';
  place_type?: PlaceTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  elevation?: number | null;
  composition?: CompositionEnum | null;
  description?: string | null;
  orientation?: number | null;
  substance_extracted?: SubstanceEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface ProductIdentity {
  /** UUID for the feature. */
  id: string;
}

export interface RailwayLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'railway';
  railway_use?: RailwayUseEnum | null;
  track_type?: TrackTypeEnum | null;
  vehicle_type?: VehicleTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  nzgb_id?: unknown;
  route?: string | null;
  route2?: string | null;
  route3?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface RailwayStation {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'rail_station';
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Relief {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'waterfall';
  name?: string | null;
  height?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface ReliefLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'cliff_edge' | 'cutting_edge' | 'embankment' | 'rapid' | 'slip_edge' | 'waterfall' | 'waterfall_edge';
  relief_use?: ReliefUseEnum | null;
  name?: string | null;
  height?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface ReliefPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'height' | 'sinkhole';
  name?: string | null;
  display?: DisplayEnum | null;
  elevation?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface ResidentialArea {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'residential_area';
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface RoadLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'road';
  hierarchy?: string | null;
  status?: StatusEnum | null;
  name?: string | null;
  highway_number?: string | null;
  lane_count?: number | null;
  surface?: SurfaceEnum | null;
  way_count?: WayCountEnum | null;
  width_indicator?: 'w' | null;
  road_access?: RoadAccessEnum | null;
  name_id?: unknown;
  rna_sufi?: unknown;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Runway {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'runway';
  runway_use?: RunwayUseEnum | null;
  status?: StatusEnum | null;
  surface?: SurfaceEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Structure {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'dry_dock' | 'fish_farm' | 'marine_farm' | 'reservoir' | 'siphon' | 'tank';
  lid_type?: LidTypeEnum | null;
  tank_type?: string | null;
  subtype?: StructureSubTypeEnum | null;
  species?: SpeciesEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  stored_item?: StoredItemEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface StructureLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type:
    | 'boatramp'
    | 'boom'
    | 'breakwater'
    | 'cableway_industrial'
    | 'cableway_people'
    | 'dam'
    | 'flume'
    | 'ladder'
    | 'marine_farm'
    | 'ski_lift'
    | 'ski_tow'
    | 'slipway'
    | 'spillway_edge'
    | 'walkwire'
    | 'water_race'
    | 'weir'
    | 'wharf'
    | 'wharf_edge';
  structure_use?: StructureUseEnum | null;
  species?: SpeciesEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  material?: MaterialEnum | null;
  material_conveyed?: MaterialConveyedEnum | null;
  restrictions?: RestrictionsEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface StructurePoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type:
    | 'beacon'
    | 'bivouac'
    | 'buoy'
    | 'chimney'
    | 'dredge'
    | 'flare'
    | 'floodgate'
    | 'gate'
    | 'ladder'
    | 'mast'
    | 'redoubt'
    | 'shaft'
    | 'siphon'
    | 'stockyard'
    | 'tank'
    | 'tower'
    | 'well'
    | 'windmill'
    | 'wreck';
  structure_use?: StructureUseEnum | null;
  tank_type?: 'uncovered' | 'water' | 'surge chamber' | null;
  subtype?: StructureSubTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  location?: LocationEnum | null;
  height?: number | null;
  orientation?: number | null;
  material?: MaterialEnum | null;
  restrictions?: RestrictionsEnum | null;
  stored_item?: StoredItemEnum | null;
  wreck_of?: WreckOfEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

/**
 * Identity columns shared by every file in the dataset.
 */
export interface TopoIdentity {
  /** UUID for the feature. */
  id: string;
}

export interface TrackLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'track';
  track_use?: TrackUseEnum | null;
  track_type?: TrackTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface TransportPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'ford' | 'helipad';
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface TrigPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'trig';
  trig_type?: TrigTypeEnum | null;
  name?: string | null;
  code?: string | null;
  elevation?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface TunnelLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'tunnel';
  tunnel_use?: TunnelUseEnum | null;
  tunnel_use2?: TunnelUse2Enum | null;
  subtype?: TunnelSubTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface UtilityLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'pipeline' | 'powerline' | 'telephone';
  utility_use?: UtilityUseEnum | null;
  support_type?: SupportTypeEnum | null;
  status?: StatusEnum | null;
  name?: string | null;
  visibility?: VisibilityEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface UtilityPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'gas_valve' | 'geo_bore' | 'pylon';
  name?: string | null;
  orientation?: number | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Vegetation {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'exotic' | 'native' | 'scattered_scrub' | 'scrub';
  subtype?: SubTypeEnum | null;
  species?: SpeciesEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface VegetationLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'shelter_belt';
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface VegetationPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'tree';
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface Water {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'canal' | 'lagoon' | 'lake' | 'pond' | 'river';
  water_use?: WaterUseEnum | null;
  hierarchy?: string | null;
  name?: string | null;
  group_name?: string | null;
  nzgb_feat_id?: unknown;
  height?: number | null;
  elevation?: number | null;
  perennial?: PerennialEnum | null;
  temperature?: TemperatureEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface WaterLine {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'canal' | 'drain' | 'river';
  hierarchy?: string | null;
  name?: string | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}

export interface WaterPoint {
  /** UUID for the feature. */
  id: string;
  updated_at: Record<string, unknown>;
  /** Default at write time: today. */
  created_at: Record<string, unknown>;
  t50_fid?: unknown;
  type: 'rock' | 'soakhole' | 'spring' | 'waterfall';
  name?: string | null;
  height?: number | null;
  orientation?: number | null;
  temperature_indicator?: TemperatureIndicatorEnum | null;
  /** WKB geometry. Validation only checks presence + non-null; semantic checks live elsewhere. */
  geometry: unknown;
  bbox?: BBox;
}
