name: airport
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  # Only keep NZ datasets for initial load.
  #  - source: kart@data.koordinates.com:linz/cook-islands-airport-polygons-topo-125k-zone4
  #    name: cook_islands_airport_polygons
  #    mapping:
  #      t50_fid: $
  #      type: airport
  #      name: $
  #      theme: transport
  #      metadata: null
  #  - source: kart@data.koordinates.com:linz/niue-airport-polygons-topo-150k
  #    mapping:
  #      t50_fid: null # FIXME: needs lookup
  #      type: airport
  #      name: $
  #      theme: transport
  #      metadata: null
  - source: kart@data.koordinates.com:linz/nz-airport-polygons-topo-150k
    mapping:
      t50_fid: $
      type: airport
      name: $
      theme: transport
      metadata: null
  - source: kart@data.koordinates.com:linz/nz-chatham-island-airport-polygons-topo-150k
    mapping:
      t50_fid: $
      type: airport
      name: $
      theme: transport
      metadata: null
