name: bridge_line
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  # FIXME: needs lookup for t50_fid
  #  - source: kart@data.koordinates.com:linz/cook-islands-bridge-centrelines-topo-125k-zone4
  #    name: cook_islands_bridge_centrelines
  #    mapping:
  #      t50_fid: $
  #      type: $use_1
  #      subtype: $use_2
  #      construction_type: $constr_typ
  #      status: $status
  #      name: $name
  #      theme: transport
  #      metadata: null
  - source: kart@data.koordinates.com:linz/nz-bridge-centrelines-topo-150k
    mapping:
      t50_fid: $
      type: $use_1
      subtype: $use_2
      construction_type: $constr_typ
      status: $status
      name: $name
      theme: transport
      metadata: null
    corrections:
      - column: type
        replace:
          foot traffic: foot_traffic
  - source: kart@data.koordinates.com:linz/nz-chatham-island-bridge-centrelines-topo-150k
    mapping:
      t50_fid: $
      type: $use_1
      subtype: $use_2
      construction_type: $constr_typ
      status: $status
      name: $name
      theme: transport
      metadata: null
    corrections:
      - column: type
        replace:
          foot traffic: foot_traffic
  # FIXME: needs lookup for t50_fid
#  - source: kart@data.koordinates.com:linz/tokelau-bridge-centrelines-topo-125k
#    mapping:
#      t50_fid: $
#      type: $use_1
#      subtype: $use_2
#      construction_type: $constr_typ
#      status: $status
#      name: $name
#      theme: transport
#      metadata: null
#    corrections:
#      - column: type
#        replace:
#          foot traffic: foot_traffic
