name: nztopo50_carto_symbol
target_repo: topographic-product-data
target_epsg: EPSG:2193

lookups:
  - name: landuse
    source:
      url: git@github.com:linz/topographic-data
      dataset: landuse
    columns: [id]
    geometry: true

  - name: road_line
    source:
      url: git@github.com:linz/topographic-data
      dataset: road_line
    columns: [id, highway_number]
    geometry: true

datasets:
  - source:
      url: git@github.com:linz/topographic-source-data
      dataset: golf_sym
    name: golf_sym
    joins:
      - lookup: landuse
        predicate: within
    mapping:
      source_id: $landuse.id
      type: golf_course
      label: null
      orientation: null
      t50_fid: null

  - source:
      url: git@github.com:linz/topographic-source-data
      dataset: mine_sym
    name: mine_sym
    joins:
      - lookup: landuse
        predicate: within
    mapping:
      source_id: $landuse.id
      type: $mine_vis
      t50_fid: null
      label: null
      orientation: null
    corrections:
      - column: type
        replace:
          training: mine_training
          opencast: mine_opencast
          underground: mine_underground

  - source:
      url: git@github.com:linz/topographic-source-data
      dataset: linz_highway_sh
    name: linz_highway_sh
    joins:
      - lookup: road_line
        predicate: nearest
        max_distance: 1
    mapping:
      source_id: $road_line.id
      type: highway_shield
      label: $road_line.highway_number
      orientation: null
      t50_fid: null
