name: nztopo50_dms_grid
target_repo: topographic-product-data
target_epsg: EPSG:4326 # Todo: labels have to be WGS84 (EPSG:4326) - confirm if geoms should be stored in NZTM (EPSG:2193)
datasets:
  # any valid source is fine. The fixups function supplies every row and column.
  - source: kart@data.koordinates.com:linz/nz-airport-polygons-topo-150k
    name: nztopo50_dms_grid
    mapping:
      t50_fid: null
      direction: { source: null, fixup: true }
      value: { source: null, fixup: true }
    fixups:
      - fn: generate_dms_grid_features
