name: railway_point
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  - source: kart@data.koordinates.com:linz/nz-rail-station-points-topo-150k
    mapping:
      t50_fid: $
      type: station
      name: $name
      theme: transport
      metadata: null
