name: relief_line
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  - source: kart@data.koordinates.com:linz/cook-islands-cliff-edges-topo-125k-zone4
    name: cook_islands_cliff_edges_topo_125k_zone4
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-cliff-edges-topo-150k
    name: nz_cliff_edges_topo_150k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-antipodes-island-cliff-edges-topo-125k
    name: nz_antipodes_island_cliff_edges_topo_125k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-auckland-island-cliff-edges-topo-150k
    name: nz_auckland_island_cliff_edges_topo_150k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-bounty-islands-cliff-edges-topo-125k
    name: nz_bounty_islands_cliff_edges_topo_125k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-campbell-island-motu-ihupuku-cliff-edges-topo-150k
    name: nz_campbell_island_motu_ihupuku_cliff_edges_topo_150k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-chatham-island-cliff-edges-topo-150k
    name: nz_chatham_island_cliff_edges_topo_150k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-kermadec-is-cliff-edges-topo-125k
    name: nz_kermadec_is_cliff_edges_topo_125k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-ross-dependency-cliff-edges-ant-150k
    name: nz_ross_dependency_cliff_edges_ant_150k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-ross-dependency-ice-cliff-edges-ant-150k
    name: nz_ross_dependency_ice_cliff_edges_ant_150k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-snares-island-tini-heke-cliff-edges-topo-125k
    name: nz_snares_island_tini_heke_cliff_edges_topo_125k
    mapping:
      t50_fid: $
      type: cliff_edge
  - source: kart@data.koordinates.com:linz/nz-cutting-edges-topo-150k
    name: nz_cutting_edges_topo_150k
    mapping:
      t50_fid: $
      type: cutting_edge
  - source: kart@data.koordinates.com:linz/cook-islands-embankment-centrelines-topo-125k-zone3
    name: cook_islands_embankment_centrelines_topo_125k_zone3
    mapping:
      t50_fid: $
      type: embankment
      relief_use: $embkmt_use
      name: $
  - source: kart@data.koordinates.com:linz/cook-islands-embankment-centrelines-topo-125k-zone4
    name: cook_islands_embankment_centrelines_topo_125k_zone4
    mapping:
      t50_fid: $
      type: embankment
      relief_use: $embkmt_use
      name: $
  - source: kart@data.koordinates.com:linz/nz-embankment-centrelines-topo-150k
    name: nz_embankment_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: embankment
      relief_use: $embkmt_use
      name: $
  - source: kart@data.koordinates.com:linz/nz-slip-edges-topo-150k
    name: nz_slip_edges_topo_150k
    mapping:
      t50_fid: $
      type: slip_edge
  - source: kart@data.koordinates.com:linz/nz-rapid-centrelines-topo-150k
    name: nz_rapid_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: rapid
      name: $
  - source: kart@data.koordinates.com:linz/nz-waterfall-centrelines-topo-150k
    name: nz_waterfall_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: waterfall
      height: $
      name: $
  - source: kart@data.koordinates.com:linz/nz-waterfall-edges-topo-150k
    name: nz_waterfall_edges_topo_150k
    mapping:
      t50_fid: $
      type: waterfall_edge
      height: $
      name: $
