name: utility_line
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  - source: kart@data.koordinates.com:linz/nz-pipeline-centrelines-topo-150k
    name: nz_pipeline_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: pipeline
      utility_use: $pipe_use
      visibility: $
  - source: kart@data.koordinates.com:linz/nz-powerline-centrelines-topo-150k
    name: nz_powerline_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: powerline
      support_type: $support_ty
  - source: kart@data.koordinates.com:linz/nz-chatham-island-powerline-centrelines-topo-150k
    name: nz_chatham_island_powerline_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: powerline
      support_type: $support_ty
  - source: kart@data.koordinates.com:linz/nz-telephone-centrelines-topo-150k
    name: nz_telephone_centrelines_topo_150k
    mapping:
      t50_fid: $
      type: telephone
