name: vegetation_point
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  # Only keep NZ datasets for initial load.
  #  - source: kart@data.koordinates.com:linz/cook-islands-tree-points-topo-125k-zone3
  #    name: cook_islands_tree_points_zone3
  #    mapping:
  #      t50_fid: $
  #      type: tree
  #      theme: landcover
  #      metadata: null
  #  - source: kart@data.koordinates.com:linz/cook-islands-tree-points-topo-125k-zone4
  #    name: cook_islands_tree_points_zone4
  #    mapping:
  #      t50_fid: $
  #      type: tree
  #      theme: landcover
  #      metadata: null
  #  - source: kart@data.koordinates.com:linz/niue-tree-points-topo-150k
  #    mapping:
  #      t50_fid: $
  #      type: tree
  #      theme: landcover
  #      metadata: null
  - source: kart@data.koordinates.com:linz/nz-tree-points-topo-150k
    mapping:
      t50_fid: $
      type: tree
      theme: landcover
      metadata: null
  - source: kart@data.koordinates.com:linz/nz-chatham-island-tree-points-topo-150k
    mapping:
      t50_fid: $
      type: tree
      theme: landcover
      metadata: null
  # needs t50_fid backfilled
  #  - source: kart@data.koordinates.com:linz/nz-kermadec-is-tree-points-topo-125k
  #    mapping:
  #      t50_fid: $
  #      type: tree
  #      theme: landcover
  #      metadata: null
  # Only keep NZ datasets for initial load.
  #  - source: kart@data.koordinates.com:linz/tokelau-tree-points-topo-125k
  #    mapping:
  #      t50_fid: $
  #      type: tree
  #      theme: landcover
  #      metadata: null
