name: water_point
target_repo: topographic-data
target_epsg: EPSG:4167
datasets:
  - source: kart@data.koordinates.com:linz/nz-kermadec-is-rock-points-topo-125k
    mapping:
      feature_type: rock
      name: $
  - source: kart@data.koordinates.com:linz/nz-campbell-island-motu-ihupuku-rock-points-topo-150k
    mapping:
      feature_type: rock
      name: $
  - source: kart@data.koordinates.com:linz/nz-bounty-islands-rock-points-topo-125k
    mapping:
      feature_type: rock
      name: $
  - source: kart@data.koordinates.com:linz/nz-antipodes-island-rock-points-topo-125k
    mapping:
      feature_type: rock
      name: $
  - source: kart@data.koordinates.com:linz/nz-auckland-island-rock-points-topo-150k
    mapping:
      feature_type: rock
      name: $
  - source: kart@data.koordinates.com:linz/nz-chatham-island-rock-points-topo-150k
    mapping:
      feature_type: rock
      name: $
  - source: kart@data.koordinates.com:linz/nz-rock-points-topo-150k
    mapping:
      feature_type: rock
      name: $