import { emitFile, getDoc } from '@typespec/compiler';
import type { Model, Enum, Union, Type } from '@typespec/compiler';

import { toPascalCase } from './utils.ts';

export async function emitTypeScript(
  program: any,
  outputFile: string,
  models: Map<string, Model>,
  enums: Map<string, Enum>,
  unions: Map<string, Union>,
) {
  function getJSDocComment(type: Type): string {
    const doc = getDoc(program, type);
    if (!doc) return '';
    const lines = doc.trim().split('\n');
    if (lines.length === 1) {
      return `  /** ${lines[0]} */\n`;
    }
    return `  /**\n${lines.map((line) => `   * ${line}`).join('\n')}\n   */\n`;
  }

  function getTsType(type: Type): string {
    switch (type.kind) {
      case 'Intrinsic':
        if (type.name === 'void') return 'void';
        if (type.name === 'never') return 'never';
        if (type.name === 'null') return 'null';
        if (type.name === 'unknown') return 'unknown';
        return 'any';
      case 'String':
        return JSON.stringify(type.value);
      case 'Number':
        return String(type.value);
      case 'Boolean':
        return String(type.value);
      case 'Scalar':
        switch (type.name) {
          case 'string':
            return 'string';
          case 'boolean':
            return 'boolean';
          case 'int32':
          case 'int64':
          case 'int16':
          case 'int8':
          case 'uint32':
          case 'uint16':
          case 'uint8':
          case 'float32':
          case 'float64':
          case 'numeric':
          case 'integer':
          case 'safeint':
          case 'float':
          case 'decimal':
          case 'decimal128':
            return 'number';
          case 'utcDateTime':
          case 'offsetDateTime':
          case 'plainDate':
          case 'plainTime':
          case 'duration':
          case 'url':
            return 'string';
          default:
            return type.name ? toPascalCase(type.name) : 'any';
        }
      case 'Enum':
        return toPascalCase(type.name);
      case 'Union':
        if (type.name) {
          return toPascalCase(type.name);
        }
        const unionTypes = Array.from(type.variants.values()).map((v) => getTsType(v.type));
        const uniqueUnionTypes = Array.from(new Set(unionTypes));
        return uniqueUnionTypes.join(' | ');
      case 'Tuple':
        return `[${type.values.map(getTsType).join(', ')}]`;
      case 'Model':
        if (type.name === 'Array') {
          if (type.indexer) {
            return `${getTsType(type.indexer.value)}[]`;
          }
          return 'any[]';
        }
        if (type.name === 'Record') {
          if (type.indexer) {
            return `Record<${getTsType(type.indexer.key)}, ${getTsType(type.indexer.value)}>`;
          }
          return 'Record<string, any>';
        }
        if (type.name && type.name !== 'object') {
          return toPascalCase(type.name);
        }
        if (type.properties.size === 0) {
          return 'Record<string, unknown>';
        }
        const props: string[] = [];
        for (const prop of type.properties.values()) {
          props.push(`${prop.name}${prop.optional ? '?' : ''}: ${getTsType(prop.type)}`);
        }
        return `{ ${props.join('; ')} }`;
      case 'ModelProperty':
        return getTsType(type.type);
      case 'EnumMember':
        return type.value !== undefined ? JSON.stringify(type.value) : JSON.stringify(type.name);
      case 'UnionVariant':
        return getTsType(type.type);
      default:
        return 'any';
    }
  }

  let code = `/**\n * This file was automatically generated by the TypeSpec TypeScript emitter.\n * Do not edit this file manually.\n */\n\n`;

  // Generate Enums as Type Aliases (erasable syntax)
  const sortedEnums = Array.from(enums.values()).sort((a, b) => a.name.localeCompare(b.name));
  for (const e of sortedEnums) {
    const doc = getDoc(program, e);
    const comment = doc
      ? `/**\n${doc
          .trim()
          .split('\n')
          .map((l) => ` * ${l}`)
          .join('\n')}\n */\n`
      : '';
    const memberValues = Array.from(e.members.values()).map((member) =>
      member.value !== undefined ? JSON.stringify(member.value) : JSON.stringify(member.name),
    );
    code += `${comment}export type ${toPascalCase(e.name)} = ${memberValues.join(' | ')};\n\n`;
  }

  // Generate Unions
  const sortedUnions = Array.from(unions.values()).sort((a, b) => a.name!.localeCompare(b.name!));
  for (const u of sortedUnions) {
    const doc = getDoc(program, u);
    const comment = doc
      ? `/**\n${doc
          .trim()
          .split('\n')
          .map((l) => ` * ${l}`)
          .join('\n')}\n */\n`
      : '';
    const unionTypes = Array.from(u.variants.values()).map((v) => getTsType(v.type));
    const uniqueUnionTypes = Array.from(new Set(unionTypes));
    code += `${comment}export type ${toPascalCase(u.name!)} = ${uniqueUnionTypes.join(' | ')};\n\n`;
  }

  // Generate Models
  const sortedModels = Array.from(models.values()).sort((a, b) => a.name.localeCompare(b.name));
  for (const m of sortedModels) {
    const doc = getDoc(program, m);
    const comment = doc
      ? `/**\n${doc
          .trim()
          .split('\n')
          .map((l) => ` * ${l}`)
          .join('\n')}\n */\n`
      : '';
    code += `${comment}export interface ${toPascalCase(m.name)} {\n`;
    if (m.indexer) {
      const keyType = getTsType(m.indexer.key);
      const valueType = getTsType(m.indexer.value);
      code += `  [key: ${keyType}]: ${valueType};\n`;
    }
    for (const prop of m.properties.values()) {
      const propComment = getJSDocComment(prop);
      code += `${propComment}  ${prop.name}${prop.optional ? '?' : ''}: ${getTsType(prop.type)};\n`;
    }
    code += '}\n\n';
  }

  await emitFile(program, {
    path: outputFile,
    content: code,
  });
}
