import { emitFile, getDirectoryPath, getDoc, joinPaths } from '@typespec/compiler';
import type { EmitContext, Enum, Model, Program, Type, Union } from '@typespec/compiler';
import { unsafe_mutateSubgraphWithNamespace } from '@typespec/compiler/experimental';
import { getVersioningMutators } from '@typespec/versioning';

import { collectTypes, toPascalCase } from './utils.ts';

function formatPropName(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

export function generateTypeScriptCode(
  program: Program,
  models: Map<string, Model>,
  enums: Map<string, Enum>,
  unions: Map<string, Union>,
): string {
  function getJSDocComment(type: Type): string {
    const doc = getDoc(program, type);
    if (!doc) return '';
    const lines = doc.trim().split('\n');
    if (lines.length === 1) {
      return `  /** ${lines[0]} */\n`;
    }
    return `  /**\n${lines.map((line) => `   * ${line}`).join('\n')}\n   */\n`;
  }

  function getTsType(type: Type): string {
    switch (type.kind) {
      case 'Intrinsic':
        if (type.name === 'void') return 'void';
        if (type.name === 'never') return 'never';
        if (type.name === 'null') return 'null';
        if (type.name === 'unknown') return 'unknown';
        return 'any';
      case 'String':
        return JSON.stringify(type.value);
      case 'Number':
        return String(type.value);
      case 'Boolean':
        return String(type.value);
      case 'Scalar':
        switch (type.name) {
          case 'string':
            return 'string';
          case 'boolean':
            return 'boolean';
          case 'int32':
          case 'int64':
          case 'int16':
          case 'int8':
          case 'uint32':
          case 'uint16':
          case 'uint8':
          case 'float32':
          case 'float64':
          case 'numeric':
          case 'integer':
          case 'safeint':
          case 'float':
          case 'decimal':
          case 'decimal128':
            return 'number';
          case 'utcDateTime':
          case 'offsetDateTime':
          case 'plainDate':
          case 'plainTime':
          case 'duration':
          case 'url':
            return 'string';
          default:
            return type.name ? toPascalCase(type.name) : 'any';
        }
      case 'Enum':
        return toPascalCase(type.name);
      case 'Union':
        if (type.name) {
          return toPascalCase(type.name);
        }
        const unionTypes = Array.from(type.variants.values()).map((v) => getTsType(v.type));
        const uniqueUnionTypes = Array.from(new Set(unionTypes));
        return uniqueUnionTypes.join(' | ');
      case 'Tuple':
        return `[${type.values.map(getTsType).join(', ')}]`;
      case 'Model':
        if (type.name === 'Array') {
          if (type.indexer) {
            return `${getTsType(type.indexer.value)}[]`;
          }
          return 'any[]';
        }
        if (type.name === 'Record') {
          if (type.indexer) {
            return `Record<${getTsType(type.indexer.key)}, ${getTsType(type.indexer.value)}>`;
          }
          return 'Record<string, any>';
        }
        if (type.name && type.name !== 'object') {
          return toPascalCase(type.name);
        }
        if (type.properties.size === 0) {
          return 'Record<string, unknown>';
        }
        const props: string[] = [];
        for (const prop of type.properties.values()) {
          props.push(`${formatPropName(prop.name)}${prop.optional ? '?' : ''}: ${getTsType(prop.type)}`);
        }
        return `{ ${props.join('; ')} }`;
      case 'ModelProperty':
        return getTsType(type.type);
      case 'EnumMember':
        return type.value !== undefined ? JSON.stringify(type.value) : JSON.stringify(type.name);
      case 'UnionVariant':
        return getTsType(type.type);
      default:
        return 'any';
    }
  }

  let code = `/**\n * This file was automatically generated by the TypeSpec TypeScript emitter.\n * Do not edit this file manually.\n */\n\n`;

  // Generate Enums as Type Aliases (erasable syntax)
  const sortedEnums = Array.from(enums.values()).sort((a, b) => a.name.localeCompare(b.name));
  for (const e of sortedEnums) {
    const doc = getDoc(program, e);
    const comment = doc
      ? `/**\n${doc
          .trim()
          .split('\n')
          .map((l) => ` * ${l}`)
          .join('\n')}\n */\n`
      : '';
    const memberValues = Array.from(e.members.values()).map((member) =>
      member.value !== undefined ? JSON.stringify(member.value) : JSON.stringify(member.name),
    );
    code += `${comment}export type ${toPascalCase(e.name)} = ${memberValues.join(' | ')};\n\n`;
  }

  // Generate Unions
  const sortedUnions = Array.from(unions.values()).sort((a, b) => (a.name ?? '').localeCompare(b.name ?? ''));
  for (const u of sortedUnions) {
    const doc = getDoc(program, u);
    const comment = doc
      ? `/**\n${doc
          .trim()
          .split('\n')
          .map((l) => ` * ${l}`)
          .join('\n')}\n */\n`
      : '';
    const unionTypes = Array.from(u.variants.values()).map((v) => getTsType(v.type));
    const uniqueUnionTypes = Array.from(new Set(unionTypes));
    code += `${comment}export type ${toPascalCase(u.name ?? '')} = ${uniqueUnionTypes.join(' | ')};\n\n`;
  }

  // Generate Models
  const sortedModels = Array.from(models.values()).sort((a, b) => a.name.localeCompare(b.name));
  for (const m of sortedModels) {
    const doc = getDoc(program, m);
    const comment = doc
      ? `/**\n${doc
          .trim()
          .split('\n')
          .map((l) => ` * ${l}`)
          .join('\n')}\n */\n`
      : '';
    const extendsClause = m.baseModel?.name ? ` extends ${toPascalCase(m.baseModel.name)}` : '';
    code += `${comment}export interface ${toPascalCase(m.name)}${extendsClause} {\n`;
    if (m.indexer) {
      const keyType = getTsType(m.indexer.key);
      const valueType = getTsType(m.indexer.value);
      code += `  [key: ${keyType}]: ${valueType};\n`;
    }
    for (const prop of m.properties.values()) {
      const propComment = getJSDocComment(prop);
      code += `${propComment}  ${formatPropName(prop.name)}${prop.optional ? '?' : ''}: ${getTsType(prop.type)};\n`;
    }
    code += '}\n\n';
  }

  return code;
}

export async function emitTypeScript(
  context: EmitContext<any>,
  outputTarget: string,
  unversionedModels?: Map<string, Model>,
  unversionedEnums?: Map<string, Enum>,
  unversionedUnions?: Map<string, Union>,
): Promise<void> {
  const { program } = context;
  const topoNs = program.getGlobalNamespaceType().namespaces.get('Topography');

  if (topoNs) {
    const mutators = getVersioningMutators(program, topoNs);
    if (mutators && mutators.kind === 'versioned') {
      const outputDir = outputTarget.endsWith('.ts') ? getDirectoryPath(outputTarget) : outputTarget;
      const versionList: string[] = [];

      for (const snapshot of mutators.snapshots) {
        const versionStr = String(snapshot.version.value ?? snapshot.version.name);
        versionList.push(versionStr);
        const versionSubdir = joinPaths(outputDir, `v${versionStr}`);
        const versionFile = joinPaths(versionSubdir, 'index.ts');

        const { type: mutatedNs } = unsafe_mutateSubgraphWithNamespace(program, [snapshot.mutator], topoNs);

        const snapshotModels = new Map<string, Model>();
        const snapshotEnums = new Map<string, Enum>();
        const snapshotUnions = new Map<string, Union>();

        collectTypes(mutatedNs as any, snapshotModels, snapshotEnums, snapshotUnions);

        const code = generateTypeScriptCode(program, snapshotModels, snapshotEnums, snapshotUnions);
        await emitFile(program, { path: versionFile, content: code });
      }

      const latestVersionStr = versionList[versionList.length - 1];
      let indexCode = `/**\n * This file was automatically generated by the TypeSpec TypeScript emitter.\n * Do not edit this file manually.\n *\n * Points to the latest schema version (v${latestVersionStr}).\n */\n\n`;
      indexCode += `export * from './v${latestVersionStr}/index.ts';\n\n`;
      for (const v of versionList) {
        const identifier = `v${v.replace(/[^a-zA-Z0-9_$]/g, '_')}`;
        indexCode += `export * as ${identifier} from './v${v}/index.ts';\n`;
      }

      const mainIndexFile = joinPaths(outputDir, 'index.ts');
      await emitFile(program, { path: mainIndexFile, content: indexCode });
      return;
    }
  }

  // Unversioned fallback
  const models = unversionedModels ?? new Map<string, Model>();
  const enums = unversionedEnums ?? new Map<string, Enum>();
  const unions = unversionedUnions ?? new Map<string, Union>();

  const code = generateTypeScriptCode(program, models, enums, unions);
  const targetFile = outputTarget.endsWith('.ts') ? outputTarget : joinPaths(outputTarget, 'index.ts');
  await emitFile(program, { path: targetFile, content: code });
}
