name: Pull Request Containers

on:
  pull_request:

jobs:
  build-container:
    uses: ./.github/workflows/containers.yml
    with:
      manifest: |
        {
          "map": ["pr-${{ github.event.number }}","pr-${{ github.event.number }}-{{ github.sha }}"],
          "kart": ["pr-${{ github.event.number }}","pr-${{ github.event.number }}-{{ github.sha }}"]
        }
      environment: nonprod
    secrets: inherit

  test-kart:
    needs: build-container
    uses: ./.github/workflows/data-review.yml
    with:
      clone_url: https://github.com/linz/topographic-test-data.git
      head_ref: master
      environment: nonprod
      changed_datasets_only: false
      output: file:///tmp/topographic-data/
      kart_version: 'pr-${{ github.event.number }}'
