on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
      - run: npm run check
      - run: npm run test

      - name: Python CI
        uses: ./.github/actions/python-ci

  build-container:
    uses: ./.github/workflows/containers.yml
    with:
      manifest: "{ \"map\": [], \"kart\": [] }"
    secrets: inherit
