name: Test Data PR Review Workflow
on: pull_request

jobs:
  test:
    uses: ./.github/workflows/data-review.yml
    with:
      clone_url: https://github.com/blacha/kart-test.git
      head_ref: master
      environment: nonprod
      changed_datasets_only: false
      output: file://$(pwd)/test-output/
      kart_version: latest
