name: visual-diff

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      is-pr:
        required: true
        type: boolean
      map_version:
        required: true
        type: string

jobs:
  produce-mapsheets:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    name: Produce Png Mapsheets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_SCREENSHOT }}

      - name: Produce mapsheets
        run: |
          docker run --rm \
          -v ${PWD}:${PWD} \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION ghcr.io/linz/topographic-system/map:${{ inputs.map_version }} \
          visual-diff \
          --output $PWD/.artifacts/visual-snapshots \
          --project s3://linz-topography-nonprod/qgis/latest/nztopo50map/nz-topo50-map.json

      - name: Save snapshots
        uses: linz/action-visual-snapshot@v2.1
        with:
          save-only: true
          snapshot-path: .artifacts/visual-snapshots

  visual-diff:
    environment: ${{ inputs.environment }}
    if: ${{ inputs.is-pr }}
    permissions:
      id-token: write
      contents: write
      checks: write
    needs: produce-mapsheets
    name: Compare Visual Diff
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_SCREENSHOT }}

      - name: Diff snapshots
        id: visual-snapshots-diff
        uses: linz/action-visual-snapshot@v2.1
        env:
          GITHUB_WORKFLOW: push
        with:
          storage-prefix: ${{ inputs.environment == 'prod' && 's3://linz-topography-screenshot' || 's3://linz-topography-screenshot-nonprod' }}
          storage-url: 'https://d2glsbt6gvd4ll.cloudfront.net'
